# Generated by Django 3.1 on 2023-11-26 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.EmailValidator(message='Введите корректный email', whitelist=['localhost', 'my_local'])], verbose_name='emaill'),
        ),
    ]
