# Generated by Django 3.1 on 2023-11-27 00:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='int_list_comma',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='list_comma'),
        ),
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.validate_ipv4_address, django.core.validators.validate_ipv6_address, django.core.validators.validate_ipv46_address], verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.URLValidator(message='Введите корректный URL', schemes=['https'])], verbose_name='url'),
        ),
    ]
