# Generated by Django 3.1 on 2023-11-27 00:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231127_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='int_list_sep',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?::(-)?\\d+)*\\Z'), code='invalid', message='Используйте двоеточие между числами')], verbose_name='list sep'),
        ),
    ]
