# Generated by Django 3.1 on 2023-11-28 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_interval_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interval_length',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=9, message='Строка длинее 9 символов'), django.core.validators.MinLengthValidator(limit_value=3, message='Строка короче 3 символов')], verbose_name='interval length'),
        ),
    ]
