# Generated by Django 3.1 on 2023-11-28 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_interval_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'jpg'], message='Не тот формат файла')], verbose_name='file'),
        ),
    ]
