# Generated by Django 3.1 on 2023-11-28 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='file/', validators=[django.core.validators.validate_image_file_extension], verbose_name='file'),
        ),
    ]
