# Generated by Django 3.1 on 2023-11-28 11:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20231128_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[blog.models.validate_date_of_birth], verbose_name='date of birth'),
        ),
    ]
